### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by zuoshouxin123** [sharmakamal1201/online-map-matching#1]
Hi, thanks for your code. Could you tell me which papers or references i can learn?

**Comment by sharmakamal1201** [comment]
Refernces :
1. S. Taguchi, S. Koide and T. Yoshimura, "Online Map Matching With Route Prediction," in IEEE Transactions on Intelligent Transportation Systems, vol. 20, no. 1, pp. 338-347, Jan. 2019, doi: 10.1109/TITS.2018.2812147.
2. http://web.mit.edu/jaillet/www/general/map_matching_itsc2012-final.pdf
